dist: xenial
sudo: true
language: python
python: "3.7"

before_install:
  - bash .install_leveldb.sh

install:
  - pip install git+https://github.com/lbryio/torba.git
  - pip install -e .[test]
  - git clone https://github.com/lbryio/lbry.git
  - pushd lbry && pip install -e . && popd

script:
  - coverage run -p `which pytest` tests/
  - coverage run -p `which trial` --reactor=asyncio lbry/lbrynet/tests/integration/wallet/test*

after_success:
  - coverage combine
  - bash <(curl -s https://codecov.io/bash)
    #  - bash .update_image.sh;
