sudo: required
language: python

python:
  - "3.6"

before_install:
  - bash .install_leveldb.sh

install:
  - pip install -r requirements.txt
  - pip install -r requirements_testing.txt
  - pip install -e .[test]
  - git clone https://github.com/lbryio/lbry.git --branch lbryum-refactor
  - pushd lbry && sed -e '/lbryschema/d' -i setup.py && pip install -e . && popd

script:
  - coverage run -p `which pytest` tests/
  - coverage run -p `which trial` --reactor=asyncio lbry/lbrynet/tests/integration/wallet/test*

after_success:
  - coverage combine
  - bash <(curl -s https://codecov.io/bash)
    #  - bash .update_image.sh;
